# Generated by Django 4.2 on 2023-05-09 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cool', models.BooleanField(default=False)),
                ('time', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500, null=True)),
                ('volume', models.FloatField(default=0, null=True)),
                ('alcool', models.FloatField(default=0, null=True)),
                ('ebc', models.FloatField(default=0, null=True)),
                ('ibu', models.FloatField(default=0, null=True)),
                ('cost', models.FloatField(default=0, null=True)),
                ('sale', models.FloatField(default=0, null=True)),
                ('private', models.BooleanField(default=True)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockYeast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StockYeasts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Yeasts', to='main.recipe')),
                ('stockYeast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Yeasts', to='main.stockyeast')),
            ],
        ),
        migrations.CreateModel(
            name='StockMalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50, null=True)),
                ('ebc', models.IntegerField(default=2)),
                ('producer', models.CharField(max_length=50, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StockMalts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockHop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pellet', models.BooleanField(default=True)),
                ('alpha', models.FloatField(default=0)),
                ('producer', models.CharField(max_length=50, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StockHops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StockExtras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='yeast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='main.yeast'),
        ),
        migrations.CreateModel(
            name='Malt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Malts', to='main.recipe')),
                ('stockMalt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Malts', to='main.stockmalt')),
            ],
        ),
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('boiling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hops', to='main.boiling')),
                ('stockHop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hops', to='main.stockhop')),
            ],
        ),
        migrations.CreateModel(
            name='Fermentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(default=19)),
                ('time', models.IntegerField(default=21)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fermentations', to='main.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('boiling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Extras', to='main.boiling')),
                ('stockExtra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Extras', to='main.stockextra')),
            ],
        ),
        migrations.CreateModel(
            name='Brewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(default=52)),
                ('time', models.IntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Brewings', to='main.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='boiling',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Boilings', to='main.recipe'),
        ),
    ]
