# Generated by Django 4.2 on 2023-05-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='family',
            field=models.CharField(choices=[('LAGER', 'Lager'), ('PILSNER', 'Pilsner'), ('WHEAT_BEER', 'Wheat Beer'), ('PALE_ALE', 'Pale Ale'), ('IPA', 'IPA'), ('STOUT', 'Stout'), ('PORTER', 'Porter'), ('BELGIAN_ALE', 'Belgian Ale'), ('AMBER_ALE', 'Amber Ale'), ('BROWN_ALE', 'Brown Ale'), ('BOCK', 'Bock'), ('KOLSCH', 'Kolsch'), ('SAISON', 'Saison'), ('GOSE', 'Gose'), ('LAMBIC', 'Lambic'), ('SOUR_ALE', 'Sour Ale'), ('OTHER', 'Other')], default='LAGER', max_length=20),
        ),
    ]
