# Generated by Django 4.2 on 2023-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_like_recipe_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockextra',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockhop',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockmalt',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockyeast',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
